### ISSUE TITLE
Question re font for the Nyxt UI

### ISSUE THREAD

**Issue by Banzayka** [aadcg/nyxt-config#1]
Hi,

Many thanks for config example, used this part

(define-configuration browser
;; Sets the font for the Nyxt UI (not for webpages)
(theme (make-instance 'theme:theme :font-family "Myfont")))

Noticed that font changed in the field marked with 1 in the attached screenshot, but effect for 2-3-4 fields is zero.
It would be greatly appreciated if you kindly advise what shall be written in the config file to change font for the entire Nyxt UI.

Many thanks in advance for your help!
![Screenshot_20240819_221241](https://github.com/user-attachments/assets/b6f9b5fa-3bcf-4372-83fe-2e4c54624bee)

**Comment by aadcg** [comment]
@Banzayka, notice that the UI uses monospaced fonts as well. Does this help?

```lisp
(define-configuration browser
  (;; Sets the font for the Nyxt UI (not for webpages).
   (theme (make-instance 'theme:theme
                         :font-family "your-font"
                         :monospace-font-family "your-font"))))
```

**Comment by Banzayka** [comment]
Thanks for assitance, it almost did the trick! All fields look ok now, except for the very bottom line marked with number 3 on the above screenshot. Any ideas how to fix it?

**Comment by aadcg** [comment]
The issue is that on Nyxt version 3, the `message-buffer` isn't a buffer. That means that you can't style it with arbitrary CSS. See PR https://github.com/atlas-engineer/nyxt/pull/3164.

These changes weren't integrated in the 3-series, since it changes the API.

As of today, the options are to accept it or to run Nyxt from master (which may be less stable).
